version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db
      - redis
  db:
    container_name: db
    image: amd64/mysql
    
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
    ports:
      - ${DB_PORT}:${DB_PORT}
  redis:
    container_name: redis
    image: redis:latest

    environment:  
      -  REDIS_PORT=${REDIS_PORT}
      -  REDIS_SERVER={REDIS_SERVER}
    ports:
      - $REDIS_PORT:$REDIS_PORT


